# Generated by Django 6.0 on 2026-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egghatch',
            name='roomNo',
            field=models.IntegerField(default=0),
        ),
    ]
