# Generated by Django 6.0 on 2026-01-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0002_egghatch_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egghatch',
            name='roomNo',
        ),
        migrations.AddField(
            model_name='egghatch',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hatches', to='eggCount.rooms'),
        ),
        migrations.AlterField(
            model_name='egghatch',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomNo',
            field=models.IntegerField(unique=True),
        ),
    ]
