# Generated by Django 6.0 on 2026-01-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0003_remove_egghatch_roomno_egghatch_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egghatch',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatches', to='eggCount.rooms'),
        ),
    ]
