# Generated by Django 6.0 on 2026-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0004_alter_egghatch_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='egghatch',
            name='roomNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
