# Generated by Django 6.0 on 2026-01-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0005_egghatch_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egghatch',
            name='room',
        ),
        migrations.AlterField(
            model_name='egghatch',
            name='roomNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eggCount.rooms'),
        ),
    ]
