# Generated by Django 6.0 on 2026-01-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0006_remove_egghatch_room_alter_egghatch_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egghatch',
            name='roomNo',
        ),
        migrations.AddField(
            model_name='egghatch',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatches', to='eggCount.rooms'),
        ),
    ]
