# Generated by Django 6.0 on 2026-01-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0007_remove_egghatch_roomno_egghatch_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='egghatch',
            name='period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
