# Generated by Django 6.0 on 2026-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0008_egghatch_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egghatch',
            name='eggsNo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
