# Generated by Django 6.0 on 2026-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0009_alter_egghatch_eggsno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
