# Generated by Django 6.0 on 2026-01-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0010_rooms_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='egghatch',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
