# Generated by Django 6.0 on 2026-02-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0011_egghatch_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='egghatch',
            name='brokenEggs',
            field=models.IntegerField(default=0),
        ),
    ]
