# Generated by Django 6.0 on 2026-02-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0012_egghatch_brokeneggs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egghatch',
            name='remarks',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
