# Generated by Django 6.0 on 2026-03-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0013_alter_egghatch_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
