# Generated by Django 6.0 on 2026-03-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggCount', '0014_alter_rooms_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(choices=[('active', 'Active'), ('Inactive', 'inactive')], default='Active', max_length=255),
        ),
    ]
